# ----------------------------------------------------
# ビルドステージ: アプリケーションをコンパイルする
# ----------------------------------------------------
FROM golang:1.21-alpine AS builder

RUN apk add --no-cache git

WORKDIR /app

COPY db/schema.sql .
COPY api/go.mod api/go.sum ./

RUN go mod tidy
COPY api/. .
RUN go build -o go_api_server ./src/main.go

# ----------------------------------------------------
# 実行ステージ: 最小限のランタイム環境を作成する
# ----------------------------------------------------
FROM alpine:latest

RUN apk add --no-cache tzdata

WORKDIR /app

COPY --from=builder /app/go_api_server .
COPY --from=builder /app/schema.sql .

CMD ["./go_api_server"]